// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Color from "@texel/color";

var Texel = {};

var Canvas = {};

function makeSeeded(seed) {
  var state = {
    contents: seed
  };
  return function () {
    state.contents = (1103515245 * state.contents + 12345) % -2147483648;
    return -1 * state.contents / -2147483648;
  };
}

var Rng = {
  m: -2147483648,
  a: 1103515245,
  c: 12345,
  makeSeeded: makeSeeded
};

function rotatePoint(x, y, angle) {
  var cosTheta = Math.cos(angle);
  var sinTheta = Math.sin(angle);
  var xNew = x * cosTheta - y * sinTheta;
  var yNew = x * sinTheta + y * cosTheta;
  return [
          xNew,
          yNew
        ];
}

function randomBySample(sample, a, b) {
  return sample * (b - a) + a;
}

function makeCachedRng(rng, len) {
  var cachedRng = Core__Array.make(len, false).map(function (param) {
        return rng();
      });
  var index = {
    contents: 0
  };
  return function () {
    index.contents = Caml_int32.mod_(index.contents + 1 | 0, len);
    return cachedRng[index.contents];
  };
}

function updateCanvas(canvas, ctx, seed) {
  var rng = makeSeeded(seed);
  var cachedRng = makeCachedRng(rng, 50000);
  var normalSample = function () {
    while(true) {
      var u = cachedRng();
      var v = 1.7156 * (cachedRng() - 0.5);
      var x = u - 0.449871;
      var y = Math.abs(v) + 0.386595;
      var q = x * x + y * (0.196 * y - 0.25472 * x);
      if (!(q > 0.27597 && (q > 0.27846 || v * v > -4 * Math.log(u) * u * u))) {
        return v / u;
      }
      continue ;
    };
  };
  var gammaSample = function (shape) {
    var normalizedShape = shape < 1 ? shape + 1 : shape;
    var a1 = normalizedShape - 1 / 3;
    var a2 = 1 / Math.sqrt(9 * a1);
    var positiveV = function () {
      while(true) {
        var x = normalSample();
        var v = 1 + a2 * x;
        if (v > 0) {
          return [
                  x,
                  v
                ];
        }
        continue ;
      };
    };
    var acceptedV = function () {
      while(true) {
        var match = positiveV();
        var vBase = match[1];
        var x = match[0];
        var v = vBase * vBase * vBase;
        var u = cachedRng();
        if (!(u > 1 - 0.331 * Math.pow(x, 4) && Math.log(u) > 0.5 * x * x + a1 * (1 - v + Math.log(v)))) {
          return v;
        }
        continue ;
      };
    };
    var v = acceptedV();
    if (normalizedShape === shape) {
      return a1 * v;
    }
    var nonzeroRandom = function () {
      while(true) {
        var u = cachedRng();
        if (u !== 0) {
          return u;
        }
        continue ;
      };
    };
    return Math.pow(nonzeroRandom(), 1 / shape) * a1 * v;
  };
  var betaSample = function (alpha, beta) {
    var u = gammaSample(alpha);
    return u / (u + gammaSample(beta));
  };
  var random = function (a, b) {
    return cachedRng() * (b - a) + a;
  };
  var randomInt = function (a, b) {
    return cachedRng() * (b - a) + a | 0;
  };
  var makeRandomWindowInt = function (a, b) {
    var start = randomInt(a, b);
    var end = randomInt(start, b);
    return function () {
      return randomInt(start, end);
    };
  };
  var rngShuffle = function (arr) {
    return arr.map(function (v) {
                    return [
                            v,
                            rng()
                          ];
                  }).toSorted(function (param, param$1) {
                  return param[1] - param$1[1];
                }).map(function (param) {
                return param[0];
              });
  };
  var xMax = canvas.width;
  var yMax = canvas.height;
  var size = xMax > yMax ? xMax : yMax;
  var makeSplats = function (param, param$1, radiusBase, sizeNumScaler) {
    var numSplats = randomInt(param[0], param[1]);
    var startHue = random(0, 360);
    var endHueLength = random(0, 360);
    var getHue = function () {
      return randomBySample(betaSample(1.4, 5), startHue, startHue + endHueLength) % 360;
    };
    var valueFloor = random(0.2, 0.7);
    var middleAngle = random(0, 1.0);
    var angleWidth = random(0, 0.2);
    var startAngle = middleAngle - angleWidth;
    var endAngle = middleAngle + angleWidth;
    var numDropWindow = makeRandomWindowInt(param$1[0], param$1[1]);
    var getXOffset = random(0, 1) < 0.4 ? makeRandomWindowInt(0, xMax) : (function () {
          return randomInt(0, xMax);
        });
    var getYOffset = random(0, 1) < 0.4 ? makeRandomWindowInt(0, yMax) : (function () {
          return randomInt(0, yMax);
        });
    for(var _for = 0; _for <= numSplats; ++_for){
      var color = Color.convert([
            getHue(),
            1.0,
            random(valueFloor, 1.0)
          ], Color.OKHSV, Color.sRGB);
      ctx.fillStyle = Color.RGBToHex(color);
      var angle = random(startAngle, endAngle) * 2 * Math.PI;
      var cosAngle = Math.cos(angle);
      var sinAngle = Math.sin(angle);
      var xAlpha = random(2.0, 3.0);
      var yStd = random(0.1, 0.4);
      var xOffset = getXOffset();
      var yOffset = getYOffset();
      var xSizeScaler = random(0.0, 2.0);
      var ySizeScaler = random(0.0, 0.2);
      var numDrops = numDropWindow() * sizeNumScaler | 0;
      var hasVisibleDrop = false;
      for(var _for$1 = 0; _for$1 <= numDrops; ++_for$1){
        var originalx = betaSample(xAlpha, 5) * size * xSizeScaler;
        var originaly = normalSample() * yStd * size * ySizeScaler;
        var x = originalx * cosAngle - originaly * sinAngle;
        var y = originalx * sinAngle + originaly * cosAngle;
        var radius = betaSample(1.4, 5) * radiusBase | 0;
        if (radius > 0) {
          var circleX = (x | 0) + xOffset | 0;
          var circleY = (y | 0) + yOffset | 0;
          if (!hasVisibleDrop) {
            ctx.beginPath();
            hasVisibleDrop = true;
          }
          ctx.moveTo(circleX + radius | 0, circleY);
          ctx.arc(circleX, circleY, radius, 0, 2 * Math.PI);
        }

      }
      if (hasVisibleDrop) {
        ctx.fill();
      }

    }
  };
  var getBgL = function () {
    var x = rng();
    if (x < 0.4) {
      return random(0.0, 0.2);
    } else if (x < 0.6) {
      return random(0.2, 0.8);
    } else {
      return random(0.8, 1.0);
    }
  };
  var bgColor = Color.convert([
        random(0, 360),
        1.0,
        getBgL()
      ], Color.OKHSL, Color.sRGB);
  ctx.fillStyle = Color.RGBToHex(bgColor);
  ctx.fillRect(0, 0, xMax, yMax);
  var sizeNumScaler = 1.0 * random(size / 300 * 0.5, size / 300 * 1.5);
  var dynamicRadiusBase = function () {
    return betaSample(2.5, 17) * random(10, 100) * 2.0;
  };
  var makeRadiusBase = rng() > 0.5 ? (function () {
        return dynamicRadiusBase();
      }) : (function () {
        return dynamicRadiusBase();
      });
  var aSeries = random(0, 1) > 0.1;
  var bSeries = random(0, 1) > 0.5;
  var cSeries = random(0, 1) > 0.2;
  var way1 = function () {
    rngShuffle([
            (function () {
                if (aSeries) {
                  Core__Array.make(randomInt(1, 3), false).forEach(function (param) {
                        makeSplats([
                              10,
                              500
                            ], [
                              0,
                              1000
                            ], makeRadiusBase(), sizeNumScaler);
                      });
                  return ;
                }
                
              }),
            (function () {
                if (bSeries) {
                  Core__Array.make(randomInt(1, 5), false).forEach(function (param) {
                        makeSplats([
                              100,
                              200
                            ], [
                              0,
                              100
                            ], makeRadiusBase(), sizeNumScaler);
                      });
                  return ;
                }
                
              }),
            (function () {
                if (cSeries || !aSeries && !bSeries) {
                  Core__Array.make(randomInt(1, 3), false).forEach(function (param) {
                        makeSplats([
                              10,
                              20
                            ], [
                              0,
                              100
                            ], makeRadiusBase(), sizeNumScaler);
                      });
                  return ;
                }
                
              })
          ]).forEach(function (v) {
          v();
        });
  };
  var way2 = function () {
    Core__Array.make(randomInt(1, 50), false).forEach(function (param) {
          makeSplats([
                randomInt(10, 100),
                randomInt(20, 500)
              ], [
                0,
                randomInt(100, 1000)
              ], makeRadiusBase(), sizeNumScaler);
        });
  };
  if (rng() > 0.2) {
    return way1();
  } else {
    return way2();
  }
}

export {
  Texel ,
  Canvas ,
  Rng ,
  rotatePoint ,
  randomBySample ,
  makeCachedRng ,
  updateCanvas ,
}
/* @texel/color Not a pure module */
