// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OtherJs from "./other.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Color from "@texel/color";

var Texel = {};

var Canvas = {};

function create(prim) {
  return OtherJs.createCircleRenderer(prim);
}

var Renderer = {
  create: create
};

function makeSeeded(prim) {
  return OtherJs.makeSeededRng(prim);
}

var Rng = {
  makeSeeded: makeSeeded
};

function randomBySample(sample, a, b) {
  return sample * (b - a) + a;
}

function makeNormalSampler(rng) {
  var sample = function () {
    while(true) {
      var u = rng();
      var v = 1.7156 * (rng() - 0.5);
      var x = u - 0.449871;
      var y = Math.abs(v) + 0.386595;
      var q = x * x + y * (0.196 * y - 0.25472 * x);
      if (!(q > 0.27597 && (q > 0.27846 || v * v > -4 * Math.log(u) * u * u))) {
        return v / u;
      }
      continue ;
    };
  };
  return sample;
}

function makeGammaSampler(rng, normalSample) {
  return function (shape) {
    var normalizedShape = shape < 1 ? shape + 1 : shape;
    var a1 = normalizedShape - 1 / 3;
    var a2 = 1 / Math.sqrt(9 * a1);
    var positiveV = function () {
      while(true) {
        var x = normalSample();
        var v = 1 + a2 * x;
        if (v > 0) {
          return [
                  x,
                  v
                ];
        }
        continue ;
      };
    };
    var acceptedV = function () {
      while(true) {
        var match = positiveV();
        var vBase = match[1];
        var x = match[0];
        var v = vBase * vBase * vBase;
        var u = rng();
        if (!(u > 1 - 0.331 * Math.pow(x, 4) && Math.log(u) > 0.5 * x * x + a1 * (1 - v + Math.log(v)))) {
          return v;
        }
        continue ;
      };
    };
    var v = acceptedV();
    if (normalizedShape === shape) {
      return a1 * v;
    }
    var nonzeroRandom = function () {
      while(true) {
        var u = rng();
        if (u !== 0) {
          return u;
        }
        continue ;
      };
    };
    return Math.pow(nonzeroRandom(), 1 / shape) * a1 * v;
  };
}

function makeQuantileTable(sizeOpt, trainingOpt, sample) {
  var size = sizeOpt !== undefined ? sizeOpt : 2048;
  var training = trainingOpt !== undefined ? trainingOpt : 4;
  var trainingSize = Math.imul(size, training);
  var sorted = Core__Array.make(trainingSize, false).map(function (param) {
          return sample();
        }).toSorted(function (a, b) {
        return a - b;
      });
  return Core__Array.make(size, false).map(function (param, i) {
              var sourceIndex = Caml_int32.div(Math.imul(i, trainingSize - 1 | 0), size - 1 | 0);
              return sorted[sourceIndex];
            });
}

function sampleTable(table, quantile) {
  var lastIndex = table.length - 1 | 0;
  var scaledIndex = quantile * lastIndex;
  var lowerIndex = scaledIndex | 0;
  var upperIndex = lowerIndex < lastIndex ? lowerIndex + 1 | 0 : lowerIndex;
  var fraction = scaledIndex - lowerIndex;
  var lower = table[lowerIndex];
  var upper = table[upperIndex];
  return lower + (upper - lower) * fraction;
}

var tableRng = OtherJs.makeSeededRng(0.314159265);

var exactNormal = makeNormalSampler(tableRng);

var exactGamma = makeGammaSampler(tableRng, exactNormal);

function exactBeta(alpha, beta) {
  var u = exactGamma(alpha);
  return u / (u + exactGamma(beta));
}

var rawNormalTable = makeQuantileTable(undefined, 16, (function () {
        return exactNormal();
      }));

var normalTable = rawNormalTable.map(function (value, i) {
      var mirrored = rawNormalTable[(rawNormalTable.length - 1 | 0) - i | 0];
      return (value - mirrored) / 2;
    });

var beta14x5Table = makeQuantileTable(undefined, undefined, (function () {
        return exactBeta(1.4, 5);
      }));

var beta25x17Table = makeQuantileTable(undefined, undefined, (function () {
        return exactBeta(2.5, 17);
      }));

var xAlphaTables = Core__Array.make(17, false).map(function (param, i) {
      var fraction = i / 16;
      var alpha = 2 + fraction * (3 - 2);
      return makeQuantileTable(1024, undefined, (function () {
                    return exactBeta(alpha, 5);
                  }));
    });

function normal(quantile) {
  return sampleTable(normalTable, quantile);
}

function beta14x5(quantile) {
  return sampleTable(beta14x5Table, quantile);
}

function beta25x17(quantile) {
  return sampleTable(beta25x17Table, quantile);
}

function betaXAlpha5(alpha, quantile) {
  var scaledAlpha = (alpha - 2) / (3 - 2) * 16;
  var lowerIndex = scaledAlpha | 0;
  var lastIndex = 16;
  var upperIndex = lowerIndex < lastIndex ? lowerIndex + 1 | 0 : lowerIndex;
  var fraction = scaledAlpha - lowerIndex;
  var lower = sampleTable(xAlphaTables[lowerIndex], quantile);
  var upper = sampleTable(xAlphaTables[upperIndex], quantile);
  return lower + (upper - lower) * fraction;
}

var Sampling = {
  makeNormalSampler: makeNormalSampler,
  makeGammaSampler: makeGammaSampler,
  tableSize: 2048,
  trainingFactor: 4,
  makeQuantileTable: makeQuantileTable,
  sampleTable: sampleTable,
  tableRng: tableRng,
  exactNormal: exactNormal,
  exactGamma: exactGamma,
  exactBeta: exactBeta,
  rawNormalTable: rawNormalTable,
  normalTable: normalTable,
  beta14x5Table: beta14x5Table,
  beta25x17Table: beta25x17Table,
  xAlphaMin: 2,
  xAlphaMax: 3,
  xAlphaTableCount: 17,
  xAlphaTables: xAlphaTables,
  normal: normal,
  beta14x5: beta14x5,
  beta25x17: beta25x17,
  betaXAlpha5: betaXAlpha5
};

function updateCanvas(canvas, seed) {
  var renderer = OtherJs.createCircleRenderer(canvas);
  var structureRng = OtherJs.makeSeededRng(seed + 0.1013904223);
  var colorRng = OtherJs.makeSeededRng(seed + 0.3660254038);
  var geometryRng = OtherJs.makeSeededRng(seed + 0.6180339887);
  var radiusRng = OtherJs.makeSeededRng(seed + 0.7320508076);
  var random = function (rng, a, b) {
    return rng() * (b - a) + a;
  };
  var randomInt = function (rng, a, b) {
    return rng() * (b - a) + a | 0;
  };
  var makeRandomWindowInt = function (rng, a, b) {
    var start = randomInt(rng, a, b);
    var end = randomInt(rng, start, b);
    return function () {
      return randomInt(rng, start, end);
    };
  };
  var rngShuffle = function (arr) {
    return arr.map(function (v) {
                    return [
                            v,
                            structureRng()
                          ];
                  }).toSorted(function (param, param$1) {
                  return param[1] - param$1[1];
                }).map(function (param) {
                return param[0];
              });
  };
  var xMax = canvas.width;
  var yMax = canvas.height;
  var size = xMax > yMax ? xMax : yMax;
  var makeSplats = function (param, param$1, radiusBase, sizeNumScaler) {
    var numSplats = randomInt(structureRng, param[0], param[1]);
    var startHue = random(colorRng, 0, 360);
    var endHueLength = random(colorRng, 0, 360);
    var getHue = function () {
      return randomBySample(sampleTable(beta14x5Table, colorRng()), startHue, startHue + endHueLength) % 360;
    };
    var valueFloor = random(colorRng, 0.2, 0.7);
    var middleAngle = random(geometryRng, 0, 1.0);
    var angleWidth = random(geometryRng, 0, 0.2);
    var startAngle = middleAngle - angleWidth;
    var endAngle = middleAngle + angleWidth;
    var numDropWindow = makeRandomWindowInt(structureRng, param$1[0], param$1[1]);
    var getXOffset = random(geometryRng, 0, 1) < 0.4 ? makeRandomWindowInt(geometryRng, 0, xMax) : (function () {
          return randomInt(geometryRng, 0, xMax);
        });
    var getYOffset = random(geometryRng, 0, 1) < 0.4 ? makeRandomWindowInt(geometryRng, 0, yMax) : (function () {
          return randomInt(geometryRng, 0, yMax);
        });
    for(var _for = 0; _for <= numSplats; ++_for){
      var color = Color.convert([
            getHue(),
            1.0,
            random(colorRng, valueFloor, 1.0)
          ], Color.OKHSV, Color.sRGB);
      renderer.setColor(Color.RGBToHex(color));
      var angle = random(geometryRng, startAngle, endAngle) * 2 * Math.PI;
      var cosAngle = Math.cos(angle);
      var sinAngle = Math.sin(angle);
      var xAlpha = random(geometryRng, 2.0, 3.0);
      var yStd = random(geometryRng, 0.1, 0.4);
      var xOffset = getXOffset();
      var yOffset = getYOffset();
      var xSizeScaler = random(geometryRng, 0.0, 2.0);
      var ySizeScaler = random(geometryRng, 0.0, 0.2);
      var numDrops = numDropWindow() * sizeNumScaler | 0;
      for(var _for$1 = 0; _for$1 <= numDrops; ++_for$1){
        var radius = sampleTable(beta14x5Table, radiusRng()) * radiusBase | 0;
        if (radius > 0) {
          var originalx = betaXAlpha5(xAlpha, geometryRng()) * size * xSizeScaler;
          var originaly = sampleTable(normalTable, geometryRng()) * yStd * size * ySizeScaler;
          var x = originalx * cosAngle - originaly * sinAngle;
          var y = originalx * sinAngle + originaly * cosAngle;
          var circleX = (x | 0) + xOffset | 0;
          var circleY = (y | 0) + yOffset | 0;
          renderer.circle(circleX, circleY, radius);
        }

      }
    }
  };
  var getBgL = function () {
    var x = structureRng();
    if (x < 0.4) {
      return random(colorRng, 0.0, 0.2);
    } else if (x < 0.6) {
      return random(colorRng, 0.2, 0.8);
    } else {
      return random(colorRng, 0.8, 1.0);
    }
  };
  var bgColor = Color.convert([
        random(colorRng, 0, 360),
        1.0,
        getBgL()
      ], Color.OKHSL, Color.sRGB);
  renderer.setBackground(Color.RGBToHex(bgColor));
  var sizeNumScaler = 1.0 * random(structureRng, size / 300 * 0.5, size / 300 * 1.5);
  var dynamicRadiusBase = function () {
    return sampleTable(beta25x17Table, radiusRng()) * random(radiusRng, 10, 100) * 2.0;
  };
  var makeRadiusBase = structureRng() > 0.5 ? (function () {
        return dynamicRadiusBase();
      }) : (function () {
        return dynamicRadiusBase();
      });
  var aSeries = random(structureRng, 0, 1) > 0.1;
  var bSeries = random(structureRng, 0, 1) > 0.5;
  var cSeries = random(structureRng, 0, 1) > 0.2;
  var way1 = function () {
    rngShuffle([
            (function () {
                if (aSeries) {
                  Core__Array.make(randomInt(structureRng, 1, 3), false).forEach(function (param) {
                        makeSplats([
                              10,
                              500
                            ], [
                              0,
                              1000
                            ], makeRadiusBase(), sizeNumScaler);
                      });
                  return ;
                }
                
              }),
            (function () {
                if (bSeries) {
                  Core__Array.make(randomInt(structureRng, 1, 5), false).forEach(function (param) {
                        makeSplats([
                              100,
                              200
                            ], [
                              0,
                              100
                            ], makeRadiusBase(), sizeNumScaler);
                      });
                  return ;
                }
                
              }),
            (function () {
                if (cSeries || !aSeries && !bSeries) {
                  Core__Array.make(randomInt(structureRng, 1, 3), false).forEach(function (param) {
                        makeSplats([
                              10,
                              20
                            ], [
                              0,
                              100
                            ], makeRadiusBase(), sizeNumScaler);
                      });
                  return ;
                }
                
              })
          ]).forEach(function (v) {
          v();
        });
  };
  var way2 = function () {
    Core__Array.make(randomInt(structureRng, 1, 50), false).forEach(function (param) {
          makeSplats([
                randomInt(structureRng, 10, 100),
                randomInt(structureRng, 20, 500)
              ], [
                0,
                randomInt(structureRng, 100, 1000)
              ], makeRadiusBase(), sizeNumScaler);
        });
  };
  if (structureRng() > 0.2) {
    way1();
  } else {
    way2();
  }
  renderer.render();
}

export {
  Texel ,
  Canvas ,
  Renderer ,
  Rng ,
  randomBySample ,
  Sampling ,
  updateCanvas ,
}
/* tableRng Not a pure module */
