// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Draw from "./Draw.res.mjs";

self.onmessage = (function ($$event) {
    var offscreenCanvas = new OffscreenCanvas($$event.data.width, $$event.data.height);
    Draw.updateCanvas(offscreenCanvas, 1.0);
    self.postMessage({
          success: true,
          imageBitmap: offscreenCanvas.transferToImageBitmap()
        });
  });

export {
  
}
/*  Not a pure module */
